name: flutter_simple_calculator
description: Flutter widget that provides simple calculator. You can easily integrate a calculator to your apps.
version: 1.0.1
author: zuvola <zuvola@gmail.com>
homepage: https://github.com/zuvola/flutter_simple_calculator

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_grid_button: ^1.1.5
  intl: ^0.15.8
  auto_size_text: ^2.0.2
  expressions: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

